"""creat tables

Revision ID: 0c8932cad4ee
Revises: fde187d8390e
Create Date: 2023-02-07 11:11:58.534829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8932cad4ee'
down_revision = 'fde187d8390e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
